name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Create environment from environment.yml
        run: conda env create -f environment.yml

      - name: Activate Conda environment
        run: echo "conda activate qe-mini-example" >> $GITHUB_ENV

      - name: Verify environment
        run: conda list

      # Add other steps here, for example:
      - name: Build documentation
        run: |
          conda activate qe-mini-example
          sphinx-build -b html docs/ docs/_build/html